# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: "config"
    label: "配置"
    editor:
      preview: false
    files:
      - label: "条目"
        name: "navs"
        file: "_data/navs.yml"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: 名称, name: name, widget: string}
              - {label: 图标, name: icon, widget: image}
              - {label: 链接, name: url, widget: string}
              - {label: 描述, name: description, widget: string}